services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  productor-ubicaciones:
    image: kvrodriguezg/productor-ubicaciones:latest
    container_name: productor-ubicaciones
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jaaa0f5tn6flh4kw_tp?TNS_ADMIN=/app/wallet
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./wallet:/app/wallet
    depends_on:
      - rabbitmq

  productor-horarios:
    image: kvrodriguezg/productor-horarios:latest
    container_name: productor-horarios
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jaaa0f5tn6flh4kw_tp?TNS_ADMIN=/app/wallet
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./wallet:/app/wallet
    depends_on:
      - rabbitmq

  consumidor-ubicaciones:
    image: kvrodriguezg/consumidor-ubicaciones:latest
    container_name: consumidor-ubicaciones
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jaaa0f5tn6flh4kw_tp?TNS_ADMIN=/app/wallet
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./wallet:/app/wallet
    depends_on:
      - rabbitmq

  consumidor-horarios:
    image: kvrodriguezg/consumidor-horarios:latest
    container_name: consumidor-horarios
    ports:
      - "8084:8084"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./archivos_horarios:/app/archivos_horarios
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
